### ISSUE TITLE
Assertion error in make_uncertainty_submission()

### ISSUE THREAD

**Issue by yujiariyasu** [pyro-ppl/Pyro-M5-Starter-Kit#6]
error in
`assert df.shape[0] == prediction.shape[0] * 2`
prediction.shape == (385560, 28),  not (30490, 28).

```
Make uncertainty submission...
> /Users/yujiariyasu/programming/ai/kaggle/Pyro-M5-Starter-Kit/util.py(448)make_uncertainty_submission()
-> assert df.shape[0] == prediction.shape[0] * 2
(Pdb) l
443  	        prediction = prediction.reshape(-1, 28)
444  	        # the later 28 days only available 1 month before the deadline
445  	
446  	        import pdb; pdb.set_trace()
447  	
448  ->	        assert df.shape[0] == prediction.shape[0] * 2
449  	
450  	
451  	        df.iloc[:prediction.shape[0], :] = prediction
452  	        # use float_format to reduce the size of output file,
453  	        # recommended at https://www.kaggle.com/c/m5-forecasting-uncertainty/discussion/135049
(Pdb) prediction.shape
(385560, 28)
(Pdb) c
Traceback (most recent call last):
  File "model3.py", line 231, in <module>
    main(args)
  File "model3.py", line 174, in main
    m5.make_uncertainty_submission(filename + "_uncertainty" + ext, q, float_format='%.3f')
  File "/Users/yujiariyasu/programming/ai/kaggle/Pyro-M5-Starter-Kit/util.py", line 448, in make_uncertainty_submission
    assert df.shape[0] == prediction.shape[0] * 2
AssertionError
```

**Comment by yujiariyasu** [comment]
Sorry, I was mistaken!!
